name: plymouth
base: core20
version: '0.1'
summary: Plymouth snap - just for debugging purposes
description: |
  Plymouth snap - just for debugging purposes
  Remember to remove serial devices from kernel command line to get graphis.
  Run with:
    sudo plymouth.plymouthd --no-daemon --debug
  Then from other terminal:
    sudo plymouth show-splash
    sudo plymouth display-message --text="Hello world"

grade: devel
confinement: devmode

layout:
  /usr/share/plymouth:
    symlink: $SNAP/usr/share/plymouth
  /usr/share/fonts/truetype:
    symlink: $SNAP/usr/share/fonts/truetype
  /usr/lib/x86_64-linux-gnu/plymouth:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/plymouth

apps:
  plymouthd:
    command: sbin/plymouthd
  plymouth:
    command: bin/plymouth

parts:
  plymouth:
    plugin: nil
    stage-packages:
      - plymouth
      - plymouth-theme-ubuntu-logo
      - plymouth-theme-ubuntu-text
    override-prime: |
      set -ex
      snapcraftctl prime
      cp usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth.in \
          usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
      ln -sf /usr/share/plymouth/themes/ubuntu-logo/ubuntu-logo.plymouth \
          usr/share/plymouth/themes/default.plymouth
      ln -sf /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth \
          usr/share/plymouth/themes/text.plymouth
