name: plymouth
base: core22
version: '0.1'
summary: Plymouth snap - just for debugging purposes
description: |
  Plymouth snap - just for debugging purposes
  Remember to remove serial devices from kernel command line to get graphis.
  Run with:
    sudo plymouth.plymouthd --no-daemon --debug --ignore-serial-consoles --kernel-command-line=splash
  Then from other terminal:
    sudo plymouth show-splash
    sudo plymouth display-message --text="Hello world"

grade: stable
confinement: devmode

package-repositories:
 - type: apt
   ppa: alfonsosanchezbeato/build2

layout:
  /usr/share/plymouth:
    symlink: $SNAP/usr/share/plymouth
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/plymouth:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/plymouth
  /usr/lib/plymouth:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/plymouth

apps:
  plymouthd:
    command: sbin/plymouthd
  plymouth:
    command: bin/plymouth

parts:
  plymouth:
    plugin: nil
    stage-packages:
      - fonts-ubuntu
      - plymouth
      - plymouth-theme-ubuntu-logo
      - plymouth-theme-ubuntu-text
    override-prime: |
      set -ex
      snapcraftctl prime
      cp usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth.in \
          usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
      ln -sf /usr/share/plymouth/themes/ubuntu-logo/ubuntu-logo.plymouth \
          usr/share/plymouth/themes/default.plymouth
      ln -sf /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth \
          usr/share/plymouth/themes/text.plymouth
      # Leave only the font used by ubuntu-logo theme
      rm -rf usr/share/fonts/truetype/dejavu/
      mv usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf .
      rm -f usr/share/fonts/truetype/ubuntu/*
      # This is the default font for label-ft
      cp Ubuntu-R.ttf usr/share/fonts/Plymouth.ttf

      mv Ubuntu-R.ttf usr/share/fonts/truetype/ubuntu/
      # Remove more unneeded parts
      rm -rf usr/share/X11/ usr/share/libthai/

      # Use ubuntu-core theme
      printf "[Daemon]\nTheme=ubuntu-core\nShowDelay=0\nDeviceTimeout=8\n" > \
          usr/share/plymouth/plymouthd.defaults

  themes:
    plugin: dump
    source: themes
    organize:
      ubuntu-core: usr/share/plymouth/themes/ubuntu-core/
