name: plymouth
base: core22
version: '0.1'
summary: Plymouth snap - just for debugging purposes
description: |
  Plymouth snap - just for debugging purposes
  Remember to remove serial devices from kernel command line to get graphis.
  Run with:
    sudo plymouth.plymouthd --no-daemon --debug --ignore-serial-consoles --kernel-command-line=splash
  Then from other terminal:
    sudo plymouth show-splash
    sudo plymouth display-message --text="Hello world"

grade: stable
confinement: devmode

package-repositories:
 - type: apt
   ppa: alfonsosanchezbeato/build2

layout:
  /usr/share/plymouth:
    symlink: $SNAP/usr/share/plymouth
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/lib/$CRAFT_ARCH_TRIPLET/plymouth:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/plymouth
  /usr/lib/plymouth:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/plymouth

apps:
  plymouthd:
    command: usr/sbin/plymouthd
  plymouth:
    command: usr/bin/plymouth

parts:
  plymouth:
    plugin: autotools
    source: https://git.launchpad.net/~alfonsosanchezbeato/+git/plymouth
    source-type: git
    source-branch: jammy-test
    build-packages:
      - libdrm-dev
      - libgtk-3-dev
      - libpango1.0-dev
      - libpng-dev
      - libudev-dev
      - systemd
      - gettext
    stage-packages:
      - fonts-ubuntu
      - libpng16-16
      - libdrm2
      - libfreetype6
    autotools-configure-parameters:
      - --prefix=/usr
      - --includedir=/usr/include
      - --mandir=/usr/share/man
      - --infodir=/usr/share/info
      - --sysconfdir=/etc
      - --localstatedir=/var
      - --disable-option-checking
      - --disable-silent-rules
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET
      - --runstatedir=/run
      - --disable-maintainer-mode
      - --disable-dependency-tracking SYSTEMD_ASK_PASSWORD_AGENT=/bin/systemd-tty-ask-password-agent
      - --disable-documentation
      - --with-runtimedir=/run
      - --enable-pango
      - --enable-freetype
      - --enable-systemd-integration
      - --enable-static
      - --enable-tracing
      - --with-background-color=0x2c001e
      - --with-background-start-color-stop=0x2c001e
      - --with-background-end-color-stop=0x2c001e
      - --with-logo=/usr/share/plymouth/ubuntu-logo.png
      - --with-release-file=/etc/os-release
      - --without-system-root-install
      - --without-rhgb-compat-link
    override-build: |
      autoconf
      automake
      snapcraftctl build
      #cp -a themes/ubuntu-text "$CRAFT_PART_INSTALL"/usr/share/plymouth/themes/
      #cp -a themes/ubuntu-logo "$CRAFT_PART_INSTALL"/usr/share/plymouth/themes/
      rm -rf "$CRAFT_PART_INSTALL"/usr/share/plymouth/themes/*
      rm -rf "$CRAFT_PART_INSTALL"/usr/libexec
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/libbrotlienc.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/libply-boot-client.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/pkgconfig
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/label.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/details.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/fade-throbber.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/text.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/space-flares.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/tribar.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/two-step.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/ubuntu-text.*
      rm -rf "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/renderers/x11.*
      strip "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/renderers/*.so
      strip "$CRAFT_PART_INSTALL"/usr/lib/*/plymouth/*.so
    override-prime: |
      set -ex
      snapcraftctl prime
      # cp usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth.in \
      #     usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth
      # ln -sf /usr/share/plymouth/themes/ubuntu-logo/ubuntu-logo.plymouth \
      #     usr/share/plymouth/themes/default.plymouth
      # ln -sf /usr/share/plymouth/themes/ubuntu-text/ubuntu-text.plymouth \
      #     usr/share/plymouth/themes/text.plymouth
      # Leave only the font used by ubuntu-logo theme
      rm -rf usr/share/fonts/truetype/dejavu/
      mv usr/share/fonts/truetype/ubuntu/Ubuntu-R.ttf .
      rm -f usr/share/fonts/truetype/ubuntu/*
      # This is the default font for label-ft
      cp Ubuntu-R.ttf usr/share/fonts/Plymouth.ttf
      mv Ubuntu-R.ttf usr/share/fonts/truetype/ubuntu/

      # Use ubuntu-core theme
      printf "[Daemon]\nTheme=ubuntu-core\nShowDelay=0\nDeviceTimeout=8\n" > \
          usr/share/plymouth/plymouthd.defaults

      # Clean-ups
      find . -name '*.a' | xargs rm
      find . -name '*.la' | xargs rm
      rm -rf usr/share/X11/ usr/share/libthai/
      rm -rf usr/share/locale/ lib/systemd/ etc/logrotate.d/ lib/ var/
      rm -rf usr/include/ usr/sbin/plymouth-set-default-theme
      rm -rf usr/share/doc usr/share/doc-base usr/share/lintian usr/share/man
      strip usr/lib/*/* usr/bin/* usr/sbin/* || true

  themes:
    plugin: dump
    source: themes
    organize:
      ubuntu-core: usr/share/plymouth/themes/ubuntu-core/
